format = """$username@$hostname $directory$fill$git_status$git_branch
$character"""
add_newline = false

[fill]
symbol = " "

[hostname]
ssh_only = false
disabled = false
format = "[$hostname]($style)"

[username]
disabled = false
show_always = true
format = "[$user]($style)"

[directory]
truncate_to_repo = false
read_only = ""
truncation_symbol = "..."
